package defaults

import (
	"github.com/braddschick/simpdf/pkg/colors"
	"github.com/braddschick/simpdf/pkg/models"
)

var (
	Word_Title = models.Styles{
		Name:     "Title",
		TextSize: 28,
		Color:    colors.Black,
		LineSize: 33,
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Basic_Title = models.Styles{
		Name:     "Title",
		TextSize: 32,
		Color:    colors.Black,
		LineSize: 39,
		Border: models.Borders{
			Color: colors.Blue600,
			Width: models.BorderWidths{
				Bottom: 5,
				Unit: models.Units{
					Design: true,
				},
			},
		},
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Word_Subtitle = models.Styles{
		Name:     "Subtitle",
		TextSize: 11,
		Color:    colors.Grey700,
		LineSize: 19,
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Basic_Subtitle = models.Styles{
		Name:     "Subtitle",
		TextSize: 16,
		Color:    colors.Grey700,
		LineSize: 19,
		Font: models.Fonts{
			Name: "Courier",
		},
	}
	Word_Heading1 = models.Styles{
		Name:     "Heading 1",
		TextSize: 16,
		Color:    colors.LightBlue,
		LineSize: 22,
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Basic_Heading1 = models.Styles{
		Name:        "Heading 1",
		TextSize:    18,
		Color:       colors.Blue600,
		LineSize:    24,
		TextVariant: models.Variants{Bold: true},
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Word_Heading2 = models.Styles{
		Name:     "Heading 2",
		TextSize: 13,
		Color:    colors.LightBlue,
		LineSize: 19,
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Basic_Heading2 = models.Styles{
		Name:        "Heading 2",
		TextSize:    14,
		Color:       colors.Blue600,
		LineSize:    19,
		TextVariant: models.Variants{Bold: true},
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Word_Heading3 = models.Styles{
		Name:     "Heading 3",
		TextSize: 12,
		Color:    colors.Blue800,
		LineSize: 17,
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Basic_Heading3 = models.Styles{
		Name:        "Heading 3",
		TextSize:    12,
		Color:       colors.Blue600,
		LineSize:    17,
		TextVariant: models.Variants{Bold: true},
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Word_Normal = models.Styles{
		Name:     "Normal",
		TextSize: 11,
		Color:    colors.Black,
		LineSize: 15,
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Basic_Normal = models.Styles{
		Name:     "Normal",
		TextSize: 12,
		Color:    colors.Black,
		LineSize: 17,
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Word_Table = models.Styles{
		Name:     "Table",
		TextSize: 11,
		Color:    colors.Black,
		LineSize: 13,
		Font: models.Fonts{
			Name: "Arial",
		},
	}
	Basic_Table = models.Styles{
		Name:     "Table",
		TextSize: 10,
		Color:    colors.Black,
		LineSize: 14,
		Font: models.Fonts{
			Name: "Courier",
		},
		BackgroundColor: colors.White,
		Border: models.Borders{
			Color: colors.Grey700,
			Width: models.BorderWidths{
				Left:   1,
				Right:  1,
				Top:    1,
				Bottom: 1,
				Unit:   models.Units{Design: true},
			},
		},
	}
)

// WordStyle is a set of default styles that are seen in the latest version of
// Microsoft Word with the exception of using "Arial" as the default font.
var WordStyle = []models.Styles{
	Word_Title,
	Word_Subtitle,
	Word_Heading1,
	Word_Heading2,
	Word_Heading3,
	Word_Normal,
	Word_Table,
}

// BasicStyle is a set of styles that look better for a business report or
// autogenerated content.
//
// When creating your own style be sure to include at a minimum "Normal", and
// "Title" as two of the styles.
var BasicStyle = []models.Styles{
	Basic_Title,
	Basic_Subtitle,
	Basic_Heading1,
	Basic_Heading2,
	Basic_Heading3,
	Basic_Normal,
	Basic_Table,
}
